module.exports=[40762,a=>{"use strict";var b=a.i(97758);function c({children:a}){return(0,b.jsx)("html",{lang:"en",children:(0,b.jsx)("body",{children:a})})}a.s(["default",()=>c,"metadata",0,{title:"Create Next App",description:"Generated by create next app"}])}];

//# sourceMappingURL=Desktop_resume_my_resume_app_layout_tsx_daa58eb1._.js.map