// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/banners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/banners">> = Specific
  const handler = {} as typeof import("../../app/banners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../app/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/comments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/comments">> = Specific
  const handler = {} as typeof import("../../app/comments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/face_rating/basic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/face_rating/basic">> = Specific
  const handler = {} as typeof import("../../app/face_rating/basic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/image_carousel/basic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/image_carousel/basic">> = Specific
  const handler = {} as typeof import("../../app/image_carousel/basic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/image_viewer/basic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/image_viewer/basic">> = Specific
  const handler = {} as typeof import("../../app/image_viewer/basic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/image_viewer/motion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/image_viewer/motion">> = Specific
  const handler = {} as typeof import("../../app/image_viewer/motion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/input/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/input">> = Specific
  const handler = {} as typeof import("../../app/input/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/like_rating/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/like_rating">> = Specific
  const handler = {} as typeof import("../../app/like_rating/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/page">> = Specific
  const handler = {} as typeof import("../../app/page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/phone_number/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/phone_number">> = Specific
  const handler = {} as typeof import("../../app/phone_number/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/price_format/basic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/price_format/basic">> = Specific
  const handler = {} as typeof import("../../app/price_format/basic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/price_format/sale/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/price_format/sale">> = Specific
  const handler = {} as typeof import("../../app/price_format/sale/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/product/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product">> = Specific
  const handler = {} as typeof import("../../app/product/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/product/product_Variants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/product_Variants">> = Specific
  const handler = {} as typeof import("../../app/product/product_Variants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/quantity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quantity">> = Specific
  const handler = {} as typeof import("../../app/quantity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/star_rating/basic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/star_rating/basic">> = Specific
  const handler = {} as typeof import("../../app/star_rating/basic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/star_rating/fractions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/star_rating/fractions">> = Specific
  const handler = {} as typeof import("../../app/star_rating/fractions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/upvote_rating/basic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/upvote_rating/basic">> = Specific
  const handler = {} as typeof import("../../app/upvote_rating/basic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/upvote_rating/motion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/upvote_rating/motion">> = Specific
  const handler = {} as typeof import("../../app/upvote_rating/motion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/variant_color_selector/basic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/variant_color_selector/basic">> = Specific
  const handler = {} as typeof import("../../app/variant_color_selector/basic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/variant_selector/basic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/variant_selector/basic">> = Specific
  const handler = {} as typeof import("../../app/variant_selector/basic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/variant_selector/multiple/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/variant_selector/multiple">> = Specific
  const handler = {} as typeof import("../../app/variant_selector/multiple/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/variant_selector/picture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/variant_selector/picture">> = Specific
  const handler = {} as typeof import("../../app/variant_selector/picture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
