var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/variant_selector/multiple/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b12351de._.js")
R.c("server/chunks/ssr/Desktop_resume_my_resume_7e565179._.js")
R.c("server/chunks/ssr/Desktop_resume_my_resume_a6077442._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1c9b71c1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f410d28d._.js")
R.c("server/chunks/ssr/36bdf_next_dist_8eb6dc3e._.js")
R.c("server/chunks/ssr/Desktop_resume_my_resume_app_642d6e1c._.js")
R.c("server/chunks/ssr/36bdf_next_dist_client_components_builtin_global-error_8adc21de.js")
R.c("server/chunks/ssr/Desktop_resume_my_resume_app_layout_tsx_daa58eb1._.js")
R.c("server/chunks/ssr/36bdf_next_dist_client_components_afd63264._.js")
R.c("server/chunks/ssr/36bdf_next_dist_client_components_builtin_forbidden_e23fd030.js")
R.c("server/chunks/ssr/36bdf_next_dist_client_components_builtin_unauthorized_0aa56d6e.js")
R.c("server/chunks/ssr/e4f50__next-internal_server_app_variant_selector_multiple_page_actions_ca225dcb.js")
R.m(8153)
module.exports=R.m(8153).exports
