var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5adf84cd._.js")
R.c("server/chunks/ssr/Desktop_resume_my_resume_7e565179._.js")
R.c("server/chunks/ssr/36bdf_next_dist_373f867d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__564690ae._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f410d28d._.js")
R.c("server/chunks/ssr/36bdf_next_dist_8eb6dc3e._.js")
R.c("server/chunks/ssr/Desktop_resume_my_resume_app_642d6e1c._.js")
R.c("server/chunks/ssr/3d860_resume_my_resume__next-internal_server_app__global-error_page_actions_6259618d.js")
R.m(61506)
module.exports=R.m(61506).exports
