var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/variant_color_selector/basic/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__464c8777._.js")
R.c("server/chunks/ssr/Desktop_resume_my_resume_7e565179._.js")
R.c("server/chunks/ssr/Desktop_resume_my_resume_2dbee426._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1c9b71c1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f410d28d._.js")
R.c("server/chunks/ssr/36bdf_next_dist_8eb6dc3e._.js")
R.c("server/chunks/ssr/Desktop_resume_my_resume_app_642d6e1c._.js")
R.c("server/chunks/ssr/36bdf_next_dist_client_components_builtin_global-error_8adc21de.js")
R.c("server/chunks/ssr/Desktop_resume_my_resume_app_layout_tsx_daa58eb1._.js")
R.c("server/chunks/ssr/36bdf_next_dist_client_components_afd63264._.js")
R.c("server/chunks/ssr/36bdf_next_dist_client_components_builtin_forbidden_e23fd030.js")
R.c("server/chunks/ssr/36bdf_next_dist_client_components_builtin_unauthorized_0aa56d6e.js")
R.c("server/chunks/ssr/e4f50__next-internal_server_app_variant_color_selector_basic_page_actions_06d3a205.js")
R.m(28175)
module.exports=R.m(28175).exports
